
# Database
db.url=jdbc:postgresql://localhost:5432/sante_lims
db.username=postgres
db.password=adminpassword
db.pool.size=10

# SMTP Email (Gmail example)
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=yourlab@gmail.com
mail.smtp.password=ehok zgst zoja ysie
mail.smtp.auth=true
mail.smtp.starttls=true
mail.from=aduraayeni5@gmail.com
mail.from.name=Sante Diagnostics

# Application
app.name=Sante Diagnostics LIMS
app.base.url=http://localhost:8080